// ═══════════════════════════════════════════════
// EARTH RESOURCE INTELLIGENCE — CURATED DATASET
// The eight foundational resource categories. Local, static,
// epistemic-confidence-tagged. No external APIs.
// ═══════════════════════════════════════════════

export const EARTH_RESOURCES = [
  {
    id: 'electricity_energy',
    category: 'ELECTRICITY_ENERGY',
    name: 'Electricity / Energy',
    keywords: ['electricity', 'energy', 'power grid', 'solar', 'wind power', 'fossil fuel', 'kilowatt', 'megawatt'],
    description: 'The universal currency of modern civilisation. Powers AI, transportation, industry, communications, cooling, and manufacturing.',
    forms: ['liquid', 'gas', 'solid', 'plasma'],
    formationProcess: 'Generated from primary sources: fossil fuels, nuclear fission, solar radiation, wind, hydro, geothermal.',
    extractionMethods: ['fossil combustion', 'nuclear fission', 'photovoltaic conversion', 'wind turbines', 'hydroelectric dams'],
    processingSteps: ['generation', 'transmission', 'distribution', 'storage'],
    primaryUses: ['AI compute', 'electric vehicles', 'industrial motors', 'data centers', 'heating and cooling'],
    secondaryUses: ['communications', 'medical equipment', 'water treatment', 'food refrigeration'],
    valueDrivers: ['energy_transition', 'technological_innovation', 'industrial_output'],
    environmentalImpact: 60, energyIntensity: 100, waterIntensity: 40,
    geopoliticalPower: 90, futureRelevance: 100, confidence: 0.95,
  },
  {
    id: 'copper',
    category: 'COPPER',
    name: 'Copper',
    keywords: ['copper', 'wiring', 'electrical grid'],
    description: 'The backbone of electrification. Essential for electrical grids, motors, EVs, data centers, electronics, and renewable energy.',
    forms: ['raw_ore', 'concentrate', 'refined_metal', 'alloy'],
    formationProcess: 'Formed in porphyry copper deposits, volcanic arcs, and sedimentary layers over millions of years.',
    extractionMethods: ['open-pit mining', 'underground mining', 'solvent extraction', 'electrowinning'],
    processingSteps: ['crushing', 'grinding', 'flotation', 'smelting', 'electrorefining'],
    primaryUses: ['electrical wiring', 'electric motors', 'transformers', 'EV batteries', 'renewable energy systems'],
    secondaryUses: ['plumbing', 'architecture', 'coinage', 'antimicrobial surfaces'],
    valueDrivers: ['energy_transition', 'industrial_output', 'technological_innovation'],
    environmentalImpact: 70, energyIntensity: 55, waterIntensity: 60,
    geopoliticalPower: 80, futureRelevance: 100, confidence: 0.95,
  },
  {
    id: 'fresh_water',
    category: 'FRESH_WATER',
    name: 'Fresh Water',
    keywords: ['fresh water', 'freshwater', 'water supply', 'groundwater', 'aquifer', 'desalination', 'drinking water', 'river', 'watershed'],
    description: 'The source of all biological life. Required for agriculture, cities, industry, semiconductor manufacturing, and energy production.',
    forms: ['liquid', 'solid', 'gas'],
    formationProcess: 'Part of the hydrological cycle: evaporation, condensation, precipitation, and groundwater recharge.',
    extractionMethods: ['surface water diversion', 'groundwater pumping', 'desalination', 'rainwater harvesting'],
    processingSteps: ['filtration', 'disinfection', 'desalination', 'distribution'],
    primaryUses: ['agriculture', 'drinking water', 'industrial cooling', 'semiconductor fabrication'],
    secondaryUses: ['energy production', 'recreation', 'ecosystem support'],
    valueDrivers: ['water_security', 'food_security', 'human_health'],
    environmentalImpact: 30, energyIntensity: 20, waterIntensity: 100,
    geopoliticalPower: 85, futureRelevance: 100, confidence: 0.98,
  },
  {
    id: 'rare_earth_elements',
    category: 'RARE_EARTH_ELEMENTS',
    name: 'Rare-Earth Elements',
    keywords: ['rare earth', 'rare-earth', 'neodymium', 'dysprosium', 'permanent magnet'],
    description: 'Seventeen chemically similar elements critical for magnets, electronics, defense, robotics, and aerospace.',
    forms: ['raw_ore', 'concentrate', 'refined_metal', 'alloy'],
    formationProcess: 'Found in carbonatite and alkaline igneous rocks; formed through mantle processes and hydrothermal alteration.',
    extractionMethods: ['open-pit mining', 'in-situ leaching', 'ion-adsorption clays'],
    processingSteps: ['mineral separation', 'acid leaching', 'solvent extraction', 'metal reduction'],
    primaryUses: ['permanent magnets', 'electric motors', 'smartphone components', 'laser systems', 'defense technologies'],
    secondaryUses: ['wind turbines', 'EV drivetrains', 'catalysts', 'phosphors'],
    valueDrivers: ['technological_innovation', 'military_power', 'industrial_output'],
    environmentalImpact: 90, energyIntensity: 70, waterIntensity: 70,
    geopoliticalPower: 95, futureRelevance: 95, confidence: 0.9,
  },
  {
    id: 'lithium_battery_minerals',
    category: 'LITHIUM_BATTERY_MINERALS',
    name: 'Lithium / Battery Minerals',
    keywords: ['lithium', 'battery mineral', 'spodumene', 'cobalt', 'nickel', 'battery storage', 'lithium-ion'],
    description: 'The foundation of energy storage. Powers electric vehicles, grid storage, and portable electronics. Takes the forms of spodumene ore, brine, carbonate, and hydroxide.',
    forms: ['brine', 'raw_ore', 'concentrate', 'chemical_compound'],
    formationProcess: 'Found in continental brines, pegmatites, and sedimentary clay deposits.',
    extractionMethods: ['brine evaporation', 'hard-rock mining', 'clay processing'],
    processingSteps: ['crushing', 'flotation', 'calcination', 'carbonation', 'hydroxide precipitation'],
    primaryUses: ['lithium-ion batteries', 'grid storage', 'electric vehicles', 'consumer electronics'],
    secondaryUses: ['lubricants', 'glass', 'ceramics', 'pharmaceuticals'],
    valueDrivers: ['energy_transition', 'technological_innovation'],
    environmentalImpact: 65, energyIntensity: 50, waterIntensity: 75,
    geopoliticalPower: 85, futureRelevance: 95, confidence: 0.9,
  },
  {
    id: 'phosphate_potash',
    category: 'PHOSPHATE_POTASH',
    name: 'Phosphate & Potash',
    keywords: ['phosphate', 'potash', 'fertiliser', 'fertilizer', 'potassium', 'crop nutrient'],
    description: 'The fertiliser minerals. Essential for food production and therefore civilisation itself.',
    forms: ['raw_ore', 'concentrate', 'chemical_compound'],
    formationProcess: 'Phosphate forms in marine sedimentary deposits; potash forms in evaporated ancient seas.',
    extractionMethods: ['open-pit mining', 'solution mining', 'dredging'],
    processingSteps: ['beneficiation', 'acidulation', 'granulation', 'compaction'],
    primaryUses: ['fertilisers', 'animal feed', 'food additives'],
    secondaryUses: ['industrial chemicals', 'detergents', 'fire retardants'],
    valueDrivers: ['food_security', 'human_health'],
    environmentalImpact: 55, energyIntensity: 35, waterIntensity: 50,
    geopoliticalPower: 75, futureRelevance: 100, confidence: 0.95,
  },
  {
    id: 'uranium',
    category: 'URANIUM',
    name: 'Uranium',
    keywords: ['uranium', 'nuclear energy', 'nuclear power', 'nuclear reactor', 'enrichment'],
    description: 'The source of nuclear energy. Provides reliable, low-carbon electricity and strategic energy security.',
    forms: ['raw_ore', 'concentrate', 'isotope', 'chemical_compound'],
    formationProcess: 'Found in granite, sandstone, and unconformity deposits; formed through crustal differentiation.',
    extractionMethods: ['open-pit mining', 'underground mining', 'in-situ leaching'],
    processingSteps: ['milling', 'conversion', 'enrichment', 'fuel fabrication'],
    primaryUses: ['nuclear reactors', 'naval propulsion', 'medical isotopes'],
    secondaryUses: ['space power', 'research reactors'],
    valueDrivers: ['energy_transition', 'military_power', 'industrial_output'],
    environmentalImpact: 50, energyIntensity: 40, waterIntensity: 60,
    geopoliticalPower: 90, futureRelevance: 80, confidence: 0.9,
  },
  {
    id: 'semiconductor_materials',
    category: 'SEMICONDUCTOR_MATERIALS',
    name: 'Semiconductor Materials',
    keywords: ['semiconductor', 'silicon', 'computer chip', 'microchip', 'wafer', 'gallium', 'germanium'],
    description: 'Silicon and other materials that make computers, AI, communications, weapons, and automation possible.',
    forms: ['raw_ore', 'refined_metal', 'chemical_compound', 'mineral'],
    formationProcess: 'Silicon from quartz; gallium and germanium from bauxite and zinc ores; formed through geological and chemical processes.',
    extractionMethods: ['mining', 'chemical refining', 'crystal growth'],
    processingSteps: ['reduction', 'purification', 'crystal pulling', 'wafer slicing', 'doping'],
    primaryUses: ['computer chips', 'AI processors', 'communications equipment', 'weapons systems'],
    secondaryUses: ['solar cells', 'LEDs', 'power electronics'],
    valueDrivers: ['technological_innovation', 'military_power'],
    environmentalImpact: 80, energyIntensity: 75, waterIntensity: 85,
    geopoliticalPower: 95, futureRelevance: 100, confidence: 0.95,
  },
];

export const RESOURCE_ALTERNATIVES = {
  ELECTRICITY_ENERGY: ['renewable microgrids', 'energy storage', 'efficiency measures'],
  COPPER: ['aluminum', 'fiber optics', 'wireless transmission'],
  FRESH_WATER: ['desalination', 'water recycling', 'rainwater harvesting'],
  RARE_EARTH_ELEMENTS: ['ferrite magnets', 'recycling', 'design-for-disassembly'],
  LITHIUM_BATTERY_MINERALS: ['sodium-ion', 'solid-state', 'flow batteries'],
  PHOSPHATE_POTASH: ['composting', 'nutrient recycling', 'precision agriculture'],
  URANIUM: ['thorium', 'fusion research', 'renewables'],
  SEMICONDUCTOR_MATERIALS: ['photonics', 'graphene', 'specialised recycling'],
};