const make = (id, category, riskLevel, description, requiresUserApproval = riskLevel !== 'LOW') => ({ id, name: id.replaceAll('_', ' '), description, category, enabled: true, requiresUserApproval, riskLevel, allowedInputs: ['text'], allowedOutputs: ['text'] });

export const CAPABILITIES = [
  make('CREATE_NOTE', 'PRODUCTIVITY', 'LOW', 'Create a structured local note.'), make('ORGANIZE_NOTES', 'PRODUCTIVITY', 'LOW', 'Organize user-provided notes.'), make('SUMMARIZE_USER_PROVIDED_TEXT', 'PRODUCTIVITY', 'LOW', 'Summarize text you provide.'), make('CREATE_CHECKLIST', 'PRODUCTIVITY', 'LOW', 'Turn provided text into a checklist.'), make('CREATE_PLAN', 'PRODUCTIVITY', 'LOW', 'Draft a plan from your input.'), make('TRACK_PROJECT', 'PRODUCTIVITY', 'LOW', 'Track a project task.'), make('GENERATE_REMINDERS', 'PRODUCTIVITY', 'LOW', 'Draft reminders for review.'),
  make('SEARCH_PUBLIC_INFORMATION', 'RESEARCH', 'MEDIUM', 'Research public information.'), make('COMPARE_INFORMATION', 'RESEARCH', 'LOW', 'Compare provided information.'), make('SUMMARIZE_SOURCES', 'RESEARCH', 'LOW', 'Summarize supplied sources.'), make('EXTRACT_FACTS', 'RESEARCH', 'LOW', 'Extract facts from supplied text.'), make('BUILD_RESEARCH_REPORT', 'RESEARCH', 'MEDIUM', 'Build a research report.'),
  make('DRAFT_TEXT', 'CONTENT', 'LOW', 'Draft user-requested text.'), make('DRAFT_ARTICLE', 'CONTENT', 'LOW', 'Draft an article.'), make('DRAFT_DESCRIPTION', 'CONTENT', 'LOW', 'Draft a description.'), make('CREATE_OUTLINE', 'CONTENT', 'LOW', 'Create an outline.'), make('GENERATE_IDEAS', 'CONTENT', 'LOW', 'Generate ideas.'), make('EDIT_USER_PROVIDED_CONTENT', 'CONTENT', 'LOW', 'Edit supplied content.'),
  make('CALCULATE', 'COMPUTATION', 'LOW', 'Evaluate a basic arithmetic expression.'), make('ANALYZE_DATA', 'COMPUTATION', 'LOW', 'Analyze supplied data.'), make('TRANSFORM_DATA', 'COMPUTATION', 'LOW', 'Transform supplied data.'), make('GENERATE_TABLE', 'COMPUTATION', 'LOW', 'Format supplied data as a table.'), make('GENERATE_CHART', 'COMPUTATION', 'LOW', 'Prepare chart-ready data.'),
  make('ANALYZE_PROJECT', 'DEVELOPMENT', 'LOW', 'Analyze user-provided project context.'), make('GENERATE_CODE', 'DEVELOPMENT', 'MEDIUM', 'Prepare a code proposal.'), make('REVIEW_CODE', 'DEVELOPMENT', 'LOW', 'Review code you provide.'), make('CREATE_TESTS', 'DEVELOPMENT', 'MEDIUM', 'Prepare test proposals.'), make('IDENTIFY_BUGS', 'DEVELOPMENT', 'LOW', 'Identify bugs in supplied code.'), make('GENERATE_DOCUMENTATION', 'DEVELOPMENT', 'LOW', 'Draft documentation.')
];
export const getCapability = id => CAPABILITIES.find(capability => capability.id === id);