// ═══════════════════════════════════════════════
// PACKAGE 49 — EVIDENCE LAYER & PROVENANCE (§3, §9)
// Each evidence item carries full provenance. Disputed or
// generalized claims are explicitly labeled as such.
// This base informs simulations; it does not decide them.
// ═══════════════════════════════════════════════

export const EVIDENCE = [
  {
    id: 'ev_portugal_2001',
    claim: 'Decriminalization paired with expanded treatment was followed by reduced drug-related deaths and HIV infections.',
    origin: 'National drug policy evaluations',
    jurisdiction: 'Portugal',
    published: '2009-2015 (multiple reports)',
    methodology: 'Observational before/after national statistics',
    confidence: 'medium',
    quality: 'B',
    citation: 'Portuguese national drug strategy evaluations; EMCDDA country reports',
    disputed: false,
    last_validated: '2026-08',
    supports: ['overdose_change', 'addiction_rate', 'public_trust'],
  },
  {
    id: 'ev_regulated_alcohol',
    claim: 'Regulated legal markets substantially reduce illicit market share over time, but do not eliminate it.',
    origin: 'Historical analysis of alcohol prohibition repeal',
    jurisdiction: 'United States',
    published: 'Historical (1933+) with modern reanalysis',
    methodology: 'Historical economic analysis',
    confidence: 'medium',
    quality: 'B',
    citation: 'Economic histories of US Prohibition and repeal',
    disputed: false,
    last_validated: '2026-08',
    supports: ['organized_crime', 'government_revenue'],
  },
  {
    id: 'ev_treatment_roi',
    claim: 'Treatment investment returns multiple dollars in reduced crime and healthcare costs per dollar spent.',
    origin: 'Public health economics literature',
    jurisdiction: 'Multiple (US, EU)',
    published: '1994-2020 (meta-analyses)',
    methodology: 'Cost-benefit meta-analysis',
    confidence: 'high',
    quality: 'A',
    citation: 'NIDA principles of treatment; multiple cost-benefit meta-analyses',
    disputed: false,
    last_validated: '2026-08',
    supports: ['healthcare_costs', 'emergency_visits', 'addiction_rate'],
  },
  {
    id: 'ev_enforcement_displacement',
    claim: 'Supply-side enforcement often displaces rather than eliminates illicit markets.',
    origin: 'Criminology research literature',
    jurisdiction: 'Multiple',
    published: '2000-2020',
    methodology: 'Systematic reviews of enforcement interventions',
    confidence: 'medium',
    quality: 'B',
    citation: 'Systematic reviews on drug law enforcement and violence',
    disputed: true,
    dispute_note: 'Effect size and direction vary strongly by context; some studies find local deterrence effects.',
    last_validated: '2026-08',
    supports: ['organized_crime', 'enforcement_costs', 'crime_indicators'],
  },
  {
    id: 'ev_youth_advertising',
    claim: 'Commercial advertising of legal psychoactive products correlates with increased youth initiation.',
    origin: 'Tobacco and alcohol marketing research',
    jurisdiction: 'Multiple',
    published: '1990-2020',
    methodology: 'Longitudinal cohort studies (analogy from tobacco/alcohol)',
    confidence: 'medium',
    quality: 'B',
    citation: 'Tobacco/alcohol marketing exposure literature',
    disputed: false,
    generalized: true,
    generalization_note: 'Evidence is from tobacco/alcohol; transfer to other substances is an assumption.',
    last_validated: '2026-08',
    supports: ['youth_exposure'],
  },
  {
    id: 'ev_education_prevention',
    claim: 'Evidence-based prevention education produces modest but real reductions in initiation; scare tactics do not.',
    origin: 'Prevention science literature',
    jurisdiction: 'Multiple',
    published: '1998-2020',
    methodology: 'Randomized and quasi-experimental program evaluations',
    confidence: 'high',
    quality: 'A',
    citation: 'Prevention program meta-analyses (e.g., school-based intervention reviews)',
    disputed: false,
    last_validated: '2026-08',
    supports: ['youth_exposure', 'addiction_rate'],
  },
  {
    id: 'ev_criminalization_equity',
    claim: 'Criminal enforcement of possession has historically fallen disproportionately on marginalized communities.',
    origin: 'Government statistics and civil rights analyses',
    jurisdiction: 'United States and others',
    published: '2010-2023',
    methodology: 'Arrest and sentencing statistics analysis',
    confidence: 'high',
    quality: 'A',
    citation: 'Arrest disparity analyses of possession offenses',
    disputed: false,
    last_validated: '2026-08',
    supports: ['social_equity', 'public_trust'],
  },
];

export const evidenceFor = (metricId) => EVIDENCE.filter(e => e.supports.includes(metricId));