import { useState, useEffect } from 'react';
import { getLastDiagnostics } from '@/lib/bison/runtime/runtimeDiagnostics';
import { Button } from '@/components/ui/button';
import { Gauge, RefreshCw } from 'lucide-react';

const STATE_COLORS = {
  ACTIVE: 'bg-gold/15 text-gold',
  IDLE: 'bg-leaf/15 text-leaf',
  SUSPENDED: 'bg-secondary text-muted-foreground',
  FAILED: 'bg-destructive/15 text-destructive',
};

export default function RuntimeDiagnosticsPanel({ accent = 'hsl(0 70% 50%)' }) {
  const [snapshot, setSnapshot] = useState(null);

  useEffect(() => { setSnapshot(getLastDiagnostics()); }, []);

  return (
    <div className="glass rounded-xl p-5">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Gauge className="w-4 h-4" style={{ color: accent }} />
          <h3 className="font-heading font-semibold text-sm">Runtime Diagnostics</h3>
        </div>
        <Button onClick={() => setSnapshot(getLastDiagnostics())} variant="outline" className="border-border text-xs">
          <RefreshCw className="w-3 h-3 mr-1" /> Refresh
        </Button>
      </div>

      {!snapshot ? (
        <p className="text-sm text-muted-foreground">No diagnostics captured yet. Send a message to Bison to generate a runtime snapshot.</p>
      ) : (
        <div className="space-y-4 text-sm">
          <p className="text-xs text-muted-foreground">Captured: {new Date(snapshot.timestamp).toLocaleString()} — all values measured by instrumented code, never generated by the model.</p>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <Stat label="Intent" value={snapshot.planner?.intent || 'N/A'} />
            <Stat label="Compute Mode" value={snapshot.computeMode} />
            <Stat label="LLM Latency" value={`${snapshot.llmLatencyMs}ms`} />
            <Stat label="DB Queries" value={snapshot.database?.queries ?? 0} />
            <Stat label="Token Estimate" value={snapshot.tokens?.estimate ?? 0} />
            <Stat label="Token Budget" value={`${snapshot.planner?.estimatedTokens ?? 0} / ${snapshot.planner?.tokenBudget ?? 0}`} />
            <Stat label="Cache" value={`${snapshot.cache?.hits ?? 0} hit / ${snapshot.cache?.misses ?? 0} miss`} />
            <Stat label="API Calls" value={snapshot.apiCalls ?? 0} />
          </div>

          {snapshot.timings && Object.keys(snapshot.timings).length > 0 && (
            <div>
              <p className="text-xs font-medium text-muted-foreground mb-1">Timings</p>
              <div className="flex flex-wrap gap-2">
                {Object.entries(snapshot.timings).map(([k, v]) => (
                  <span key={k} className="px-2 py-0.5 rounded-full bg-secondary/50 text-xs">{k}: {typeof v === 'number' ? `${Math.round(v)}ms` : String(v)}</span>
                ))}
              </div>
            </div>
          )}

          {snapshot.scheduler?.length > 0 && (
            <div>
              <p className="text-xs font-medium text-muted-foreground mb-1">Module States (Execution Scheduler)</p>
              <div className="flex flex-wrap gap-2">
                {snapshot.scheduler.map(m => (
                  <span key={m.name} className={`px-2 py-0.5 rounded-full text-xs ${STATE_COLORS[m.state] || 'bg-secondary'}`}>
                    {m.name} · {m.state}{m.lastDurationMs != null ? ` · ${m.lastDurationMs}ms` : ''}
                  </span>
                ))}
              </div>
            </div>
          )}

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <div>
              <p className="text-xs font-medium text-muted-foreground mb-1">Loaded Contexts ({snapshot.planner?.requiredContexts?.length || 0})</p>
              <p className="text-xs text-muted-foreground break-words">{(snapshot.planner?.requiredContexts || []).join(', ') || 'None'}</p>
            </div>
            <div>
              <p className="text-xs font-medium text-muted-foreground mb-1">Skipped Contexts ({snapshot.planner?.skippedContexts?.length || 0})</p>
              <p className="text-xs text-muted-foreground break-words">{(snapshot.planner?.skippedContexts || []).join(', ') || 'None'}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function Stat({ label, value }) {
  return (
    <div>
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="font-medium text-xs">{String(value)}</p>
    </div>
  );
}